### ISSUE TITLE
Excelのシート名の制限より長い名称のテーブルにデータを読み込めない

### ISSUE THREAD

**Issue by kiyokura** [kiyokura/SSDTHelper#16]
Excelのシート名の制限を超える長さのテーブルにデータを投入できない問題。

**Comment by kiyokura** [comment]
ExcelReader.Readerにシート名とテーブル名のディクショナリを受け付けるオーバーロードを作る程度でよいかな？

**Comment by makowis** [comment]
@kiyokura そうですね。それがあればこの問題は解決できそうです
